//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJ_PRODUCT
    {
        public string ID { get; set; }
        public string PRODUCTNO { get; set; }
        public string PRODUCTNAME { get; set; }
        public string PRODUCTDESC { get; set; }
        public string PRODUCTSUBDESC { get; set; }
        public string PRODUCTSPEC { get; set; }
        public string PRODUCTBARCODE { get; set; }
        public string PRODUCTNODECODE { get; set; }
        public string TURNOVERRATE { get; set; }
        public string ABC { get; set; }
        public string PRODUCTCLASS { get; set; }
        public string PRODUCTTYPE { get; set; }
        public string PRODUCTTSTATE { get; set; }
        public Nullable<decimal> QUANTITY_PACK { get; set; }
        public string MAINUNIT { get; set; }
        public string BASICUNIT { get; set; }
        public string MAINTOBASICRATE { get; set; }
        public string MAINTOBASICDESC { get; set; }
        public string CREATEBY { get; set; }
        public string CREATEDATE { get; set; }
        public string MODIFYBY { get; set; }
        public string MODIFYDATE { get; set; }
        public string REMARK { get; set; }
        public string BRANDID { get; set; }
        public string BRANDNAME { get; set; }
        public string VENDORID { get; set; }
        public string VENDORNAME { get; set; }
        public string PRODUCTERID { get; set; }
        public string PRODUCTERNAME { get; set; }
        public Nullable<decimal> MARKETPRICE { get; set; }
        public Nullable<decimal> LOWESTSALEPRICE { get; set; }
        public Nullable<decimal> SELLPRICE { get; set; }
        public string ISDELICATE { get; set; }
        public string IMPORTPRODUCT { get; set; }
        public string IMAGEURL { get; set; }
        public string DEFAULTCOLOR { get; set; }
        public string PALLETEMPLTY { get; set; }
        public string PALLETENTITY { get; set; }
        public Nullable<decimal> SIZE_LENGTH { get; set; }
        public Nullable<decimal> SIZE_WIDTH { get; set; }
        public Nullable<decimal> SIZE_HEIGHT { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> NETWEIGHT { get; set; }
        public string WARNSTATE { get; set; }
        public Nullable<decimal> INV_HIGH { get; set; }
        public Nullable<decimal> INV_SAFE { get; set; }
        public Nullable<decimal> INV_ORDER { get; set; }
        public Nullable<decimal> INV_HIVEDAYS { get; set; }
        public Nullable<decimal> INV_LIMIT { get; set; }
        public string INV_HIGH_COLOR { get; set; }
        public string INV_SAFE_COLOR { get; set; }
        public string INV_ORDER_COLOR { get; set; }
        public string INV_HIVEDAYS_COLOR { get; set; }
        public string INV_LIMIT_COLOR { get; set; }
        public string CUSTOMCOL01 { get; set; }
        public string CUSTOMCOL02 { get; set; }
        public string CUSTOMCOL03 { get; set; }
        public string CUSTOMCOL04 { get; set; }
        public string CUSTOMCOL05 { get; set; }
        public string CUSTOMCOL06 { get; set; }
        public string CUSTOMCOL07 { get; set; }
        public string CUSTOMCOL08 { get; set; }
        public string CUSTOMCOL09 { get; set; }
        public string CUSTOMCOL10 { get; set; }
    }
}
