//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PACKAGE_CALLBACK
    {
        public string BILLCODE { get; set; }
        public Nullable<decimal> ROUTEPACKAGENUM { get; set; }
        public Nullable<decimal> ORDERPACKAGENUM { get; set; }
        public Nullable<decimal> PACKAGESEQ { get; set; }
        public Nullable<decimal> CIGARETTEQTY { get; set; }
        public Nullable<decimal> SHAPEDNUM { get; set; }
        public string CIGARETTECODE { get; set; }
        public string CIGARETTENAME { get; set; }
        public string CIGARETTETYPE { get; set; }
        public string ROUTECODE { get; set; }
        public Nullable<decimal> PACKAGEQTY { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public string LINECODE { get; set; }
        public Nullable<decimal> ORDERCOUNT { get; set; }
        public Nullable<decimal> ORDERSEQ { get; set; }
        public Nullable<decimal> CIGSEQ { get; set; }
        public decimal EXPORT { get; set; }
        public Nullable<decimal> PACKAGENUM { get; set; }
        public Nullable<decimal> ORDERQUANTITY { get; set; }
        public string ADDRESS { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string CUSTOMERNO { get; set; }
        public string ORDERURL { get; set; }
        public Nullable<decimal> ORDERAMOUNT { get; set; }
        public string PAYFLAG { get; set; }
        public Nullable<decimal> SEQ { get; set; }
        public Nullable<decimal> NORMALPACKAGENUM { get; set; }
        public Nullable<decimal> UNNORMALPACKAGENUM { get; set; }
        public Nullable<decimal> UNIONTASKPACKAGENUM { get; set; }
        public decimal SORTNUM { get; set; }
        public decimal CIGNUM { get; set; }
        public Nullable<decimal> SYNSEQ { get; set; }
    }
}
