//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PACKAGE_TASK
    {
        public decimal PTID { get; set; }
        public string BILLCODE { get; set; }
        public Nullable<decimal> ORDERSEQ { get; set; }
        public Nullable<decimal> PACKAGESEQ { get; set; }
        public string CIGARETTECODE { get; set; }
        public string CIGARETTENAME { get; set; }
        public Nullable<decimal> PACKAGEQTY { get; set; }
        public Nullable<decimal> CIGSEQ { get; set; }
        public Nullable<decimal> CIGHIGH { get; set; }
        public Nullable<decimal> CIGWIDTH { get; set; }
        public Nullable<decimal> CIGLENGTH { get; set; }
        public Nullable<decimal> CIGWIDTHX { get; set; }
        public Nullable<decimal> CIGHIGHY { get; set; }
        public Nullable<decimal> CIGZ { get; set; }
        public Nullable<decimal> SORTNUM { get; set; }
        public Nullable<decimal> ALLPACKAGESEQ { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> FINISHTIME { get; set; }
        public Nullable<decimal> ORDERPACKAGEQTY { get; set; }
        public Nullable<decimal> ORDERQTY { get; set; }
        public Nullable<decimal> PACKAGENO { get; set; }
        public Nullable<decimal> PACKTASKNUM { get; set; }
        public Nullable<decimal> CIGNUM { get; set; }
        public string CIGTYPE { get; set; }
        public string DOUBLETAKE { get; set; }
        public Nullable<decimal> STATE { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<decimal> PUSHSPACE { get; set; }
        public Nullable<decimal> UNIONPACKAGETAG { get; set; }
        public Nullable<decimal> CIGSTATE { get; set; }
        public Nullable<decimal> NORMAILSTATE { get; set; }
        public Nullable<decimal> NORMALQTY { get; set; }
    }
}
