//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_POKE
    {
        public decimal POKEID { get; set; }
        public string TROUGHNUM { get; set; }
        public Nullable<decimal> POKENUM { get; set; }
        public Nullable<decimal> SORTSTATE { get; set; }
        public Nullable<decimal> TASKNUM { get; set; }
        public Nullable<decimal> TASKQTY { get; set; }
        public string EXPORTNUM { get; set; }
        public Nullable<decimal> MACHINESEQ { get; set; }
        public Nullable<decimal> MAINBELT { get; set; }
        public Nullable<decimal> GROUPNO { get; set; }
        public Nullable<decimal> POKEPLACE { get; set; }
        public Nullable<decimal> UNIONSTATE { get; set; }
        public Nullable<decimal> MACHINESTATE { get; set; }
        public Nullable<decimal> MERAGENUM { get; set; }
        public Nullable<decimal> PACKAGEMACHINE { get; set; }
        public Nullable<decimal> SORTNUM { get; set; }
        public string BILLCODE { get; set; }
        public string UNIONEXPORTNUM { get; set; }
        public Nullable<decimal> UNIONTASKNUM { get; set; }
        public Nullable<decimal> SECSORTNUM { get; set; }
        public string INVFLAG { get; set; }
        public Nullable<decimal> SENDPOKENUM { get; set; }
    }
}
