//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_ORDER_H
    {
        public string BILLCODE { get; set; }
        public string COMPANYCODE { get; set; }
        public string COMPANYNAME { get; set; }
        public string BATCHCODE { get; set; }
        public Nullable<decimal> SYNSEQ { get; set; }
        public Nullable<decimal> ORDERQUANTITY { get; set; }
        public Nullable<decimal> ORDERMONEY { get; set; }
        public string CUSTOMERCODE { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string REGIONCODE { get; set; }
        public string TASKNUMBERS { get; set; }
        public string TASKBOXIES { get; set; }
        public string STATE { get; set; }
        public Nullable<decimal> DEVSEQ { get; set; }
        public Nullable<decimal> ID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public string UNSTATE { get; set; }
        public Nullable<System.DateTime> INSERTTIME { get; set; }
    }
}
