//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_SORTTROUGH
    {
        public decimal ID { get; set; }
        public string LINENUM { get; set; }
        public string TROUGHNUM { get; set; }
        public string TROUGHDESC { get; set; }
        public Nullable<decimal> ACTCOUNT { get; set; }
        public Nullable<decimal> MACHINESEQ { get; set; }
        public string CIGARETTECODE { get; set; }
        public string CIGARETTENAME { get; set; }
        public string STATE { get; set; }
        public Nullable<decimal> MANTISSA { get; set; }
        public Nullable<decimal> CIGARETTETYPE { get; set; }
        public Nullable<decimal> REPLENISHLINE { get; set; }
        public Nullable<decimal> TRANSPORTATIONLINE { get; set; }
        public Nullable<decimal> LASTMANTISSA { get; set; }
        public Nullable<decimal> TROUGHTYPE { get; set; }
        public Nullable<decimal> GROUPNO { get; set; }
        public Nullable<decimal> THRESHOLD { get; set; }
        public Nullable<decimal> BOXCOUNT { get; set; }
        public Nullable<decimal> MAINTISSALESS { get; set; }
        public Nullable<decimal> CLEARUP { get; set; }
        public Nullable<decimal> CLEARTHRESHOLD { get; set; }
        public Nullable<decimal> SEQ { get; set; }
    }
}
