//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PRODUCE_SYNSEQ
    {
        public decimal ID { get; set; }
        public Nullable<decimal> SYNSEQ { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public string PMSTATE { get; set; }
        public string TBJSTATE { get; set; }
        public Nullable<decimal> PACKAGENO { get; set; }
    }
}
