//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UN_TASK_H
    {
        public decimal TASKNUM { get; set; }
        public string LINENUM { get; set; }
        public string EXPORTNUM { get; set; }
        public string REGIONCODE { get; set; }
        public string REGIONDESC { get; set; }
        public string BILLCODE { get; set; }
        public string COMPANYCODE { get; set; }
        public string COMPANYNAME { get; set; }
        public string BATCHCODE { get; set; }
        public Nullable<decimal> SYNSEQ { get; set; }
        public string CUSTOMERCODE { get; set; }
        public Nullable<decimal> ORDERQUANTITY { get; set; }
        public string CUSTOMERNAME { get; set; }
        public Nullable<decimal> ORDERMONEY { get; set; }
        public Nullable<decimal> TASKQUANTITY { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string TASKBOX { get; set; }
        public Nullable<decimal> SORTSEQ { get; set; }
        public string LABLENUM { get; set; }
        public Nullable<System.DateTime> PLANTIME { get; set; }
        public Nullable<System.DateTime> SORTTIME { get; set; }
        public Nullable<System.DateTime> FINISHTIME { get; set; }
        public string STATE { get; set; }
        public Nullable<short> LABELBATCH { get; set; }
        public Nullable<decimal> PALLETNUM { get; set; }
        public Nullable<decimal> EXISTRCD { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<decimal> MAINBELT { get; set; }
        public Nullable<decimal> PACKAGEMACHINE { get; set; }
        public Nullable<decimal> SORTNUM { get; set; }
        public Nullable<decimal> SECSORTNUM { get; set; }
        public Nullable<System.DateTime> INSERTTIME { get; set; }
    }
}
