//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WMS_ITEM
    {
        public string ID { get; set; }
        public string DCNO { get; set; }
        public Nullable<decimal> SHIPPER_ID { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public string SHORTNAME { get; set; }
        public string SPEC { get; set; }
        public Nullable<decimal> ABCCODE { get; set; }
        public Nullable<decimal> ITEMPRICE { get; set; }
        public string SHIPTYPE { get; set; }
        public string ITEMTYPE_ID { get; set; }
        public string PRODUCEAREA { get; set; }
        public Nullable<decimal> MANUFACTURER_ID { get; set; }
        public Nullable<decimal> VENDOR_ID { get; set; }
        public string BASEUOM_ID { get; set; }
        public string DEFAULTUOM_ID { get; set; }
        public string STORAGECONDITION { get; set; }
        public Nullable<decimal> ISLOTCTRL { get; set; }
        public Nullable<decimal> SHELFLIFE { get; set; }
        public string SHELFLIFETYPE { get; set; }
        public Nullable<short> PALLETRATIO { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEUSER { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string MODIFYUSER { get; set; }
        public Nullable<decimal> ROWSTATUS { get; set; }
        public Nullable<decimal> CATID { get; set; }
        public string BIGBOX_BAR { get; set; }
        public string PACK_BAR { get; set; }
        public string ITEM_KIND { get; set; }
        public string KIND { get; set; }
        public Nullable<decimal> H_SIZE { get; set; }
        public Nullable<decimal> T_SIZE { get; set; }
        public Nullable<decimal> J_SIZE { get; set; }
        public Nullable<decimal> W_SIZE { get; set; }
        public Nullable<decimal> X_SIZE { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> FULLCOUNT { get; set; }
        public Nullable<decimal> CDTYPE { get; set; }
        public Nullable<decimal> ISCANSCANCODE { get; set; }
        public string DXTYPE { get; set; }
        public Nullable<decimal> JT_SIZE { get; set; }
        public Nullable<decimal> WZ_SIZE { get; set; }
        public Nullable<decimal> OUTTYPE { get; set; }
        public Nullable<decimal> ILENGTH { get; set; }
        public Nullable<decimal> IWIDTH { get; set; }
        public Nullable<decimal> IHEIGHT { get; set; }
        public string DOUBLETAKE { get; set; }
    }
}
