//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModle
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRODUCE_PACKAGEINFO
    {
        public decimal TASKNUM { get; set; }
        public Nullable<decimal> EXPORT { get; set; }
        public string REGIONCODE { get; set; }
        public string REGIONNAME { get; set; }
        public string CONTACTADDRESS { get; set; }
        public string SORTDATE { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string CUSTOMERCODE { get; set; }
        public string BILLCODE { get; set; }
        public string CIGARETTECODE { get; set; }
        public string CIGARETTENAME { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string ALLOWSORT { get; set; }
        public Nullable<decimal> SORTSEQ { get; set; }
        public Nullable<decimal> MACHINESEQ { get; set; }
        public string TROUGHNUM { get; set; }
        public Nullable<decimal> ORDERCOUNT { get; set; }
        public decimal SEQ { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> SENDSEQ { get; set; }
        public Nullable<decimal> SENDTASKNUM { get; set; }
        public Nullable<decimal> POKEID { get; set; }
        public string CUSTTYPE { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public string COMPLAINNUM { get; set; }
        public string SERVICENUM { get; set; }
        public Nullable<decimal> SYNSEQ { get; set; }
        public Nullable<decimal> ORDERQUANTITY { get; set; }
    }
}
